<template>
  <div
    class="
      flex
      justify-center
      items-center
      space-x-2
      py-4
    "
  >
    <div
      class="
        w-3
        h-3
        bg-faded-color
        rounded-full
        animate-bounce
        [animation-delay:-0.3s]
      "
    />
    <div
      class="
        w-3
        h-3
        bg-faded-color
        rounded-full
        animate-bounce
        [animation-delay:-0.15s]
      "
    />
    <div
      class="
        w-3
        h-3
      bg-faded-color
        rounded-full
        animate-bounce
      "
    />
  </div>
</template>
